# Generated by Django 4.2.4 on 2023-08-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Identificacion', models.CharField(max_length=20)),
                ('NombreApellidos', models.CharField(max_length=100)),
                ('Estamento', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=10)),
                ('Poblacion', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('Dependencia', models.CharField(max_length=100)),
            ],
        ),
    ]
